config/routes.rb
SampleApp::Application.routes.draw do
  resources :users

  match '/', :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  

   root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name, :password, :password_confirmation

  email_regex  = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence   => true,
  				    :format     => { :with =>  email_regex },
  				    :uniqueness => { :case_sensitive =>  false }
  validates :name,  :presence   => true,
                    :length     => { :maximum  => 50 }
  validates :password, :presence => true,
              		   :confirmation =>  true,
              		   :length => { :within => 6..40 }
  before_save :encrypt_password

  # returns true if the user's a password matches the submitted password.
  def has_password?(submitted_password)
  	# Compare encrypted_password with the encrypted versions of
  	# submitted_password
  	encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
  	user  = find_by_email(email)
  	return nil if user.nil?
  	return user if user.has_password?(submitted_password)
  end

  private

    def encrypt_password
    	self.salt = make_salt if new_record?
    	self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
    	secure_hash("#{salt}--#{string}")
    end

    def make_salt
    	secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
    	Digest::SHA2.hexdigest(string)
    end

end
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign up"
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  	@title = @user.name
  end

  def create
  	@user  = User.new(params[:user])

  	if  @user.save
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on per-page basis.
	def title
		base_title = "Ruby on Rails Tutorial Sample App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end

	# Return the logo asset
	def logo
		image_tag("logo.png", :alt => "Sample App", :class => "round")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {:size => 50})
		gravatar_image_tag(user.email.downcase, :alt  => user.name,
			                                     :class => 'gravatar',
			                                     :gravatar => options)
	end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><a href="Http://news.railstutorial.org/">News</a></li>
			<li><a href="Http://www.railstutorial.org/">Rails Tutorials</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
  		<nav class="round">
  			<ul>
  				<li><%= link_to "Home", root_path %></li>
  				<li><%= link_to "Help", help_path %></li>
  				<li><%= link_to "Sign in", '#' %></li>
  			</ul>
  		</nav>
  	</header>

app/views/layouts/_stylesheets.html.erb
<!-- [if li IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
  <!--[if li IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R<%= title %></title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
  	<%= render 'layouts/header' %>
  	<section class="round">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value  %></div>
      <%  end %>
      <%= yield %>
  	</section>
  	<%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/help.html.erb
<h1>About Us</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
	Thos os the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
  	<h2><%= pluralize(@user.errors.count, "error") %></h2>
  	<p>There were problems with the following fields:</p>
  	<ul>
  		<% @user.errors.full_messages.each do |msg| %>
  		<li><%=  msg %></li>
  		<% end  %>
  	</ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<div class="field">
	<%= f.label :name %></br>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %><br />
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
			  <%= gravatar_for @user %>
			  <%= @user.name %>
			</h1>
		</td>
		<td class="sidebar round">
			<strong>Name</strong>  <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>